name: Node.js Tests

on: ["push", "pull_request"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 15.x, 16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: npm ci
        run: npm ci
      #- run: npm run build --if-present
      #- run: npm install --global mocha
      #- run: npm install --global chai
      - name: Run tests
        run: npm test-c8
      
      - name: Make coverage report and send to coveralls
        run: npm run c8-coveralls

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}